development:
  twitter:
    access_key: 
    secret_key: 

  facebook:
    access_key: 
    secret_key: 

  github:
    access_key: 
    secret_key: 
    
  google_oauth2:
    access_key: 
    secret_key: 

  myopenid:
    store_path: /tmp
    name: myopenid
    identifier: myid.myopenid.com
