development:
  twitter:
    access_key: 'BiWXr9OHtte86x2VTZtcfg'
    secret_key: 'rduKtZftsxqjFMWAKtPgs5Ttg5oRcsmLGONH4NZQM'

  facebook:
    access_key: 328347787240063
    secret_key: 6bf33a4ff6f922c49917a5dbbe8dc729

  github:
    access_key: '77d1eb93248860d3c258'
    secret_key: 'ef148cda7859bff986757bf3c9c3a88dccdf2b73' 
    
  google_oauth2:
    access_key: 584199907644.apps.googleusercontent.com
    secret_key: q4Xf0TTbqFCEb68fHVkGi4Dc

  myopenid:
    store_path: /tmp
    name: myopenid
    identifier: shivaaqua.myopenid.com
